version: '3'
services:
    
 sim-edge-platform-node-red:
    image: "artifactory-test.siemens.net:8084/simatic_edge/releases/sim-edge-platform-node-red/sim-edge-platform-node-red:0.9.7.21"
    container_name: "sim-edge-platform-node-red"
    ports:
     - "1880:1880" 
    user: '1000:1000'
    volumes:
     - /home/$USER/sim-edge-data/sim-edge-platform-node-red:/home/nodered/node-red-home
     - /home/$USER/.ssh/:/home/nodered/.ssh
    environment:
     - SIM_EDGE_NODERED_PASS=admin123
     - http_proxy=$http_proxy
     - https_proxy=$https_proxy
     - no_proxy=$no_proxy